headline: Frontend, Backend Developer & Mentor
summary: I design and code beautifully simple things, and I love what I do.
hireMeLink: https://www.fiverr.com/martin_devs/create-node-js-reactjs-application
contact:
  headline: Love to hear from you, <br /><span className='mt-3 block' /> Get in touch ðŸ‘‹
  summary: >-
    Feel free to contact me with questions about any of my project or services.
    I'll get back to you within 24 hours!
  email: me@thereactivedeveloper.pro
  phone: '+254700207054'
  address: 347 Murang'a
social:
  github: https://github.com/marville001
  linkedin: https://www.linkedin.com/in/marville001/
  twitter: https://twitter.com/marville001
  instagram: https://instagram.com/marville001
profileImage: /profile/profileImage.jpeg
resume: /resume/resume.pdf
